- app/modules/course/views/CourseDetailsView.js
- app/router.js
- db.json
- server/index.js
Added api route /check_email for checking email for existence
> Added api route /check_email to json-server and cleared console.logs

- app/modules/login/index.js
- app/modules/login/model/loginModel.js
- app/modules/login/template/loginTemplate.html
- app/modules/login/view/loginView.js
- app/router.js
> login module.

- app/router.js
File router.js has been modified.
> Registration. Render added.

- app/modules/course/templates/courseDetailsTemplate.html
- app/modules/course/templates/courseTemplate.html
- app/modules/course/templates/sidebarTemplate.html
- app/styles/scss/modules/_course-block.scss
- app/styles/scss/modules/_template.scss
Added data-bypass in href for preventing defaults
> Accordion fixs

- app/modules/core/views/modalView.js
- app/modules/register/index.js
- app/modules/register/model/registerModel.js
- app/modules/register/template/registerTemplate.html
- app/modules/register/view/registerView.js
- app/styles/scss/modules/_modal.scss
- app/styles/scss/modules/_register-page.scss
> some fixes according remarks

- app/modules/course/templates/courseDetailsTemplate.html
- app/modules/course/templates/courseTemplate.html
- app/modules/module/templates/moduleTemplate.html
- app/styles/scss/modules/_module-block.scss
- app/styles/scss/modules/_template.scss
made iframe responsive, added variables to _template, fixed some paddings
> made iframe responsive

- app/modules/core/collections/PageableCollection.js
- app/modules/course/collections/CoursesCollection.js
- app/modules/course/views/CoursesView.js
- app/modules/filter/views/filterView.js
Fixed bug when filtering on pagination active
> Bugfix with pagination

- app/modules/course/templates/coursesTemplate.html
- app/modules/course/views/CoursesView.js
- app/router.js
- db.json
- server/index.js
> Implemented search

- app/modules/register/model/registerModel.js
- app/modules/register/template/registerTemplate.html
> Password verification done.

- app/app.js
- app/modules/module/templates/moduleTemplate.html
- app/modules/module/templates/modulesTemplate.html
- app/modules/module/views/ModuleView.js
- app/router.js
- db.json
Added arrays for different types of resources
> Added arrays for different types of resources

- app/modules/core/templates/modalTemplate.html
- app/modules/core/templates/paginationTemplate.html
- app/modules/course/views/SidebarView.js
- app/modules/test/collections/QuestionsCollection.js
- app/modules/test/collections/QuestionsPageableCollection.js
- app/modules/test/index.js
- app/modules/test/models/QuestionModel.js
- app/modules/test/models/TestModel.js
- app/modules/test/templates/testsTemplate.html
- app/modules/test/views/TestsView.js
- app/router.js
- app/styles/scss/modules/_test-block.scss
- db.json
1) change data structure according Java-back side
2) use core-popup in test-module
3) fix css-style for test-module
> Test-module improving

- app/modules/core/templates/mainContainerTemplate.html
- app/modules/module/templates/moduleTemplate.html
- app/styles/scss/modules/_module-block.scss
- app/styles/scss/modules/_template.scss
fixed padding and margin for the test button
> fixed button padding

- app/modules/test/collections/QuestionsPageableCollection.js
- app/modules/test/templates/paginationTemplate.html
- app/modules/test/views/PaginationView.js
- app/modules/test/views/TestView.js
- app/modules/test/views/TestsView.js
- app/styles/scss/modules/_test-block.scss
Please, accept my pull, because test-module don't work after last merge
But this putch will fix it!
P.S.: and some updates as for test-page UI
> fix test-page after merge with last pull-request

- app/modules/test/templates/paginationTemplate.html
- app/modules/test/templates/testTemplate.html
- app/modules/test/templates/testsTemplate.html
- app/modules/test/views/PaginationView.js
- app/modules/test/views/TestsView.js
- app/router.js
- app/styles/scss/modules/_test-block.scss
Due to the unnormal situation, please, accept pull-request in the following sequence:
1) "added momentjs"
2) my pull-request "last version UI for test-page to DEMO-2 (without express + mongoDB)"
3) "Express"
So, last pull-request must fis all unnormal bugs
> last version UI for test-page to DEMO-2 (without express + mongoDB)

- app/config.js
- app/modules/core/view.js
- app/modules/course/views/SidebarView.js
fixed bug with date localization in firefox
> fixed bug with date localization in firefox

- app/styles/scss/modules/_navbar-block.scss
- app/styles/scss/modules/_template.scss
> changed navbar to be adaptive

- app/modules/module/models/ModuleModel.js
- app/modules/module/templates/moduleTemplate.html
- app/modules/module/templates/modulesTemplate.html
- app/modules/module/views/ModuleView.js
- app/router.js
fixed links to tests on module page
> fixed links to tests on module page

- app/modules/login/view/loginView.js
- app/router.js
- app/styles/scss/modules/_login-page.scss
- package.json
- server/config.js
- server/controllers/login.js
- server/controllers/signup.js
- server/middlewares/auth.js
- server/models/user.js
- server/models/userModel.js
- server/server.js
> imprvd auth, mongoose model and hashing pass, minor style changes

- app/modules/core/models/SessionModel.js
- server/controllers/index.js
- server/controllers/menus.js
- server/middlewares/auth.js
- server/models/menu.js
- server/models/menuLink.js
- server/models/user.js
Now api response just that menu links that this user can see based on user role
> API: Menu links for menu module

- .gitignore
- app/modules/core/models/SessionModel.js
- app/modules/test/templates/testsTemplate.html
- app/modules/test/views/TestsView.js
- app/router.js
- server/controllers/answers.js
Wait expert's opinion and advices about method to save data on server :)
> save user answer on server

- app/index.html
- app/modules/module/views/CreateModuleView.js
- app/router.js
- server/controllers/modules.js
added possibility to edit existing modules
> edit_module

- app/modules/test/collections/AnswersCollection.js
- app/modules/test/views/TestsView.js
- package.json
- server/controllers/answers.js
1) preparation data: sort, controle for merge data, clean localStorage after response
2) improve save on server (using async-lib)
3) add two new methods of estimating answers
Now CRSMS offers three methods  for  answers estimating
> review save techoloqy of answers on backend

- app/app.js
- app/modules/management/collections/menuLinksCollection.js
- app/modules/management/collections/menusCollection.js
- app/modules/management/index.js
- app/modules/management/templates/managementTemplate.html
- app/modules/management/templates/managementsTemplate.html
- app/modules/management/templates/menuEditTemplate.html
- app/modules/management/templates/menuLinkEditTemplate.html
- app/modules/management/views/managementView.js
- app/modules/management/views/managementsView.js
- app/modules/management/views/menuEditView.js
- app/modules/management/views/menuLinkEditView.js
- app/modules/navigation/templates/menuTemplate.html
- app/router.js
- app/styles/scss/modules/_management-block.scss
- server/controllers/menus.js
- server/controllers/setup.js
- server/models/menu.js
- server/models/menuLink.js
They can be accessed through management/menus
> Added menus manageability in management module
